### ISSUE TITLE
tclcsv 2.4.2 does not build with gcc on Windows

### ISSUE THREAD

**Issue by PaulObermeier** [apnadkarni/tcl-csv#3]
I get the following errors when trying to compile on Windows with gcc:

generic/csv.c: In function 'csv_format_cell':
generic/csv.c:1877:49: error: invalid operands to binary - (have 'long long int' and 'char *')
         Tcl_DStringSetLength(ds, (Tcl_Size) dst - p);
                                  ~~~~~~~~~~~~~~ ^
generic/csv.c:1928:45: error: invalid operands to binary - (have 'long long int' and 'char *')
     Tcl_DStringSetLength(ds, (Tcl_Size) dst - p);


I assume, the Tcl_DStringSetLength lines should be:
     Tcl_DStringSetLength(ds, (Tcl_Size) (dst - p));

Paul

**Comment by apnadkarni** [comment]
Sigh. Sorry, Forgot to check in my work tree. Fixed and released as 2.4.3.
