### ISSUE TITLE
tclcsv 2.4.2 does not build on Linux

### ISSUE THREAD

**Issue by PaulObermeier** [apnadkarni/tcl-csv#4]
./generic/csv.c:1883:9: error: unknown type name ‘ptrdiff_t’
 1883 |         ptrdiff_t len = p - src;
      |         ^~~~~~~~~
./generic/csv.c:20:1: note: ‘ptrdiff_t’ is defined in header ‘<stddef.h>’; did you forget to ‘#include <stddef.h>’?
   19 | #include <ctype.h>
  +++ |+#include <stddef.h>

Compiler message says, what's going wrong.

**Comment by apnadkarni** [comment]
Sigh. Sorry, Forgot to check in my work tree. Fixed and released as 2.4.3.
