### ISSUE TITLE
Invalid header guard in csv.h

### ISSUE THREAD

**Issue by PaulObermeier** [apnadkarni/tcl-csv#5]
On Mac I get the following warning:

./generic/csv.h:15:9: warning: '_TCLCSV_H' is used as a header guard here, followed by #define of a different macro [-Wheader-guard]
   15 | #ifndef _TCLCSV_H
      |         ^~~~~~~~~
./generic/csv.h:16:9: note: '_TCLCSV_H_' is defined here; did you mean '_TCLCSV_H'?
   16 | #define _TCLCSV_H_
      |         ^~~~~~~~~~
      |         _TCLCSV_H

**Comment by apnadkarni** [comment]
Fixed in 2.4.3
